### ISSUE TITLE
Negative Numbers

### ISSUE THREAD

**Issue by arickGrootveld** [ACov96/dialect#1]
Negative Numbers not working on current version. 
### Code used to test this:
```
print(-1);
```
**Error thrown:**
```
Syntax error
  LexToken(MINUS,'-',1,6)
```

### Problem: 
Unable to use negative numbers at all.

### Workaround:
 You can always use 0 - $negativeNumber to get the desired result i.e.:
```
print(0-1);
```
is a workaround for the above problem that will print -1.

**Comment by ACov96** [comment]
Fixed in 0.1.13. Updating lexer to accept **-** and do conversion to float there. I may change this later depending on if we want a distinct negation operator.
